### ISSUE TITLE
Support for v18.3.1?

### ISSUE THREAD

**Issue by gbussing** [nicholas-ross/SSMS-Schema-Folders#11]
Hi,

I just upgraded to SSMS v18.3.1 and the extension does not seem to work. Is it possible that this version is not supported?

Regards.

**Comment by nicholas-ross** [comment]
I've upgraded from v18.3 to 18.3.1 and it is working ok.

Which version did you upgrade from?

v18 installs side by side with earlier versions (v17, 2016, etc). This means you need to install the extension for each SSMS version. The default location for 18 is `C:\Program Files (x86)\Microsoft SQL Server Management Studio 18\Common7\IDE\Extensions` but the SSMS installer does let you choose a different path.

If the extension is in that location then what do you see when you go to `Tools > Options > SQL Server Object Explorer > Schema Folders`?

**Comment by gbussing** [comment]
I have a different path to the extension folder (policy reasons) but other extensions kept working after the upgrade (so I think that is not the problem). The SSMS upgrade was from an older version (16.x). So after the upgrade I downloaded the latest schema folder extension version. When I go to Options I see this:
![Screenshot](https://user-images.githubusercontent.com/57133367/67841217-de99d380-faf7-11e9-8a42-8074d81f8060.PNG)

**Comment by gbussing** [comment]
It's fixed. Apparently it had something to do with the way I unzipped the .zip file. First I just dragged the content from the .zip file to the SSMS extension folder (that did not work). The second time I first unzipped the .zip file (using 7zip) and then I dragged the unziped folder to the extension folder. That way it works.
