### ISSUE TITLE
No an issue, perhaps a suggestion, if possible

### ISSUE THREAD

**Issue by BogdanBigB** [nicholas-ross/SSMS-Schema-Folders#2]
Hi again.

We are implementing a "curious" DB structure.
i.e. Shemas and Tables like 
[Current.Alert].[Alert]
[Current.System].[AlertStatus]
[Current.System].[AlertType]
etc.

It would be nice if the tree can go like this:
-Current
         -Curent.Alert
                       -Current.Alert.Alert
         -Current.System
                       -Current.System.AlertStatus
                       -Current.System.AlertType

This is how the extension actually displays this scenario:
![image](https://user-images.githubusercontent.com/25581398/33469955-b521dd4a-d6a0-11e7-90ed-9f996cd321aa.png)

**Comment by BogdanBigB** [comment]
My text in the previous comment was altered. I meant, if the tree could look like this:
![image](https://user-images.githubusercontent.com/25581398/33470002-006b1a64-d6a1-11e7-8074-0879dc121d2b.png)

**Comment by nicholas-ross** [comment]
I've been thinking about adding additional folder levels using a user defined regular expression. That way it can have folders for stored procedures based on the naming convention used, e.g. when it sees the first underscore. I will keep your structure in mind when I start to develop this.

**Comment by BogdanBigB** [comment]
Great, thanks a lot. I'll keep an eye for updates 👍

**Comment by SG12345678** [comment]
If we could write our own expressions like 
substring(name,1, charindex('_',name,charindex('_',name,1)+1))
it would be great. 
We use several "_" in our naming convention, and have lot of tables.

If it also would be possible to define a list of database.schemas an expression should apply, it would be great.

**Comment by nicholas-ross** [comment]
I did experiment with this at the time. There is a branch called FolderLevels that added a second folder level and sorting by first letter. I never got to implementing the custom sort. Between work, life and changing to a new computer, it got left behind. It has been on my mind for the next version but I cannot give you any time frame for when that would be.

**Comment by Icecoldmeat** [comment]
Hey nicholas, 

thanks for your response.
It's already wonderful to hear that you experimented with possibly adding the feature.
I will be looking forward to the next version of your plugin:)

kind regards.

**Comment by nicholas-ross** [comment]
See release [v1.4-beta2](https://github.com/nicholas-ross/SSMS-Schema-Folders/releases/tag/v1.4-beta2).

**Comment by nicholas-ross** [comment]
v1.5 added support for a second schema using a dot. [v1.6](https://github.com/nicholas-ross/SSMS-Schema-Folders/releases/tag/v1.6) added underscore as an alternate delimiter. Pattern matching will come at a later date.
