### ISSUE TITLE
2018 Reg File Missing? 

### ISSUE THREAD

**Issue by akbaltes** [nicholas-ross/SSMS-Schema-Folders#25]
Hello, 
I do not see the SkipLoading.2018.reg file in this download. Perhaps I missed a step? Thanks in advance. 

![image](https://user-images.githubusercontent.com/104165537/166555987-8d2f44d9-92f2-4a4c-97cf-8d5e9b4920d2.png)

**Comment by nicholas-ross** [comment]
Hi. It is not needed for v18. Earlier versions had restrictions on which extensions were allowed. The registry file just sets the same settings as the warning prompt SSMS would show. They removed this restriction in v18.

**Comment by akbaltes** [comment]
> Hi. It is not needed for v18. Earlier versions had restrictions on which extensions were allowed. The registry file just sets the same settings as the warning prompt SSMS would show. They removed this restriction in v18.

Thank you!
