### ISSUE TITLE
Tip when the extension does not load: try this

### ISSUE THREAD

**Issue by WaTiNL** [nicholas-ross/SSMS-Schema-Folders#29]
Maybe helpfull for others . . .

I downloaded **v1.4-beta SSMS 19** en tried to get it working with **SSMS v19.0.1** on a server running on Windows Server 2019 (1809).

I followed the instructions:

- Unblocked the zip file
- Copied folder SSMS Schema Folders to C:\Program Files (x86)\Microsoft SQL Server Management Studio 19\Common7\IDE\Extensions
- Did not work
- Checked that all dll-files where unlocked (and that was the case)
- Copied to C:\Program Files (x86)\Microsoft SQL Server Management Studio 18\Common7\IDE\Extensions
- Did not work
- Copied to C:\Program Files (x86)\Microsoft SQL Server\130\Tools\Binn\ManagementStudio\Extensions
- Copied to C:\Program Files (x86)\Microsoft SQL Server\140\Tools\Binn\ManagementStudio\Extensions
- Copied to C:\Program Files (x86)\Microsoft SQL Server\150\Tools\Binn\ManagementStudio\Extensions
- Copied to C:\Program Files (x86)\Microsoft SQL Server\160\Tools\Binn\ManagementStudio\Extensions
- Did not work
- Rebooted the server
- Did not work

**- Copied to C:\Program Files\Extensions which is E:\Program Files\Extensions**
**- Copied to C:\Program Files\Common7\IDE\Extensions which is E:\Program Files\Common7\IDE\Extensions**

And that **did work**.

**Comment by nicholas-ross** [comment]
SSMS 18 and 19 allow installing in a different location. Extensions need to be copied to the installation path that was used. If the folder in the instructions does not exist then you need to find the correct path.

It looks like your installation path was changed from "C:\Program Files (x86)\Microsoft SQL Server Management Studio 19" to "E:\Program Files". Notice that the management studio folder in the new path is missing. The uninstaller should delete only its own files, so it shouldn't delete everything in your program files folder if you decide to uninstall it.

**Comment by WaTiNL** [comment]
Yeah, I think you're right. Thanks. E:\Program Files\Extensions is a symbolic link for C:\Program Files\Extensions and I think SSMS being installed to C:\Program Files is the case. Something to be sharp on, especially when you did not install SSMS yourself, but you do install SSMS-Schema-Folders.
