### ISSUE TITLE
Will there be a GA SSMS v19-version?

### ISSUE THREAD

**Issue by hkroese** [nicholas-ross/SSMS-Schema-Folders#30]
Will there be a GA SSMS v19-version?
I'm missing this extension very much!

**Comment by nicholas-ross** [comment]
The 1.4-beta that is listed as the latest release works. Only issue is the German localisation doesn't have the new settings descriptions.

Now that 19 is released and I know it works I might remove the beta label.

**Comment by hkroese** [comment]
Would be nice! Thanks for your response.
