### ISSUE TITLE
Extension doesn't work anymore after installing SSMS 19.1

### ISSUE THREAD

**Issue by hkroese** [nicholas-ross/SSMS-Schema-Folders#32]
Extension doesn't work anymore after installing SSMS 19.1

Error in activitylog.xml:
  <entry>
    <record>246</record>
    <time>2023/05/25 12:09:24.558</time>
    <type>Warning</type>
    <source>SsmsSchemaFolders.SsmsSchemaFoldersPackage</source>
    <description>Unknown SSMS Version. Defaulting to 18.</description>
    <guid>{A88A775F-7C86-4A09-B5A6-890C4C38261B}</guid>
  </entry>

  <entry>
    <record>247</record>
    <time>2023/05/25 12:09:24.574</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>LegacySitePackage failed for package [SsmsSchemaFolders.SsmsSchemaFoldersPackage, SsmsSchemaFolders, Version=1.0.0.0, Culture=neutral, PublicKeyToken=a93ca1bbf74c67b4]Source: &apos;SsmsSchemaFolders.Ssms18&apos; Description: Unable to cast object of type &apos;Microsoft.SqlServer.Management.SqlStudio.Explorer.ObjectExplorerService&apos; to type &apos;Microsoft.SqlServer.Management.UI.VSIntegration.ObjectExplorer.IObjectExplorerService&apos;.&#x000D;&#x000A;System.InvalidCastException: Unable to cast object of type &apos;Microsoft.SqlServer.Management.SqlStudio.Explorer.ObjectExplorerService&apos; to type &apos;Microsoft.SqlServer.Management.UI.VSIntegration.ObjectExplorer.IObjectExplorerService&apos;.&#x000D;&#x000A;   at SsmsSchemaFolders.ObjectExplorerExtender.GetObjectExplorerTreeView() in C:\Users\Nicholas\Documents\Projects\SSMS-Schema-Folders\ObjectExplorerExtender.cs:line 100&#x000D;&#x000A;   at SsmsSchemaFolders.SsmsSchemaFoldersPackage.AttachTreeViewEvents()&#x000D;&#x000A;   at SsmsSchemaFolders.SsmsSchemaFoldersPackage.Initialize()&#x000D;&#x000A;   at Microsoft.VisualStudio.Shell.Package.Microsoft.VisualStudio.Shell.Interop.IVsPackage.SetSite(IServiceProvider sp)</description>
    <guid>{A88A775F-7C86-4A09-B5A6-890C4C38261B}</guid>
    <hr>80004002 - E_NOINTERFACE</hr>
    <errorinfo></errorinfo>
  </entry>

**Comment by nicholas-ross** [comment]
They changed the file version numbers in this release. Fixed in [v1.5](/nicholas-ross/SSMS-Schema-Folders/releases).

**Comment by hkroese** [comment]
Thanks for your fast reaction! Top!
