### ISSUE TITLE
SSMS Schema Folders continues to show Tables (expanding...)

### ISSUE THREAD

**Issue by ttaylor29** [nicholas-ross/SSMS-Schema-Folders#33]
Hello,

I followed the instructions and setup ssms schema folders.

When I open up my Azure db server, go to my database, open up the Tables, I always see (expanding...).

How can I fix this?

![image](https://github.com/nicholas-ross/SSMS-Schema-Folders/assets/23564255/692e1002-4f3c-44f6-b5c1-de818520f607)

To resolve, I just hit **Refresh** on the Tables and it collapse all the tables to the schemas.

Version info:

SQL Server Management Studio						19.0.20196.0+2666cdc9
SQL Server Management Objects (SMO)						16.200.48035.0+151cabf12d40a9649e575b05b1e409956d432cc9
Microsoft T-SQL Parser						16.0.22524.0+62eedb15cd3cde34e51c8fbbdf9b06e575ec912e
Microsoft Analysis Services Client Tools						16.0.19970.0
Microsoft Data Access Components (MDAC)						10.0.19041.2913
Microsoft MSXML						3.0 6.0 
Microsoft .NET Framework						4.0.30319.42000
Operating System						10.0.19044

**Comment by nicholas-ross** [comment]
That 'expanding' text is added by SSMS. It will add the first 50 tree nodes before expanding the node. If there is more than 50 then it will continue adding nodes while showing that label. It will remove the label when it has finished. I'm not sure if this is different when connecting to an Azure DB.

Do you have the same issue when disabling my extension?
`Tools > Options... > SQL Server Object Explorer > Schema Folders > Enabled: False`

If yes then try updating SSMS to version 19.1.

Do you have the same issue when first expanding the Views folder then the Tables folder?

How many tables do you have in that database?

Are you using the default options for my extension? If not then which values have you set?

Is SSMS on your local computer or do you remote desktop into a VM? Does the VM have only one cpu core?

**Comment by nicholas-ross** [comment]
I finally got access to an Azure SQL instance I could test with and have identified the cause. It might take a while before I can write a proper fix but I do have a workaround.

In the options change `Unresponsive timeout` to 3000. If you still have the problem then you can increase the value even more.

**Comment by ttaylor29** [comment]
@nicholas-ross 

That fixed it for now on my end!

Thanks for looking into it!

**Comment by nicholas-ross** [comment]
[v1.6 released.](https://github.com/nicholas-ross/SSMS-Schema-Folders/releases/tag/v1.6)
