### ISSUE TITLE
Unable to load in SSMS 19.3

### ISSUE THREAD

**Issue by acappelletti** [nicholas-ross/SSMS-Schema-Folders#41]
I followed all instructions... but seems no compatible with this release? Isn't it?

![image](https://github.com/nicholas-ross/SSMS-Schema-Folders/assets/43847440/c9cc897a-735f-4d83-a9db-f1c8ec5ff3e8)

![image](https://github.com/nicholas-ross/SSMS-Schema-Folders/assets/43847440/c4cd29bc-fa96-4617-84f1-ef8595397169)

ThanksALEN

**Comment by nicholas-ross** [comment]
You have downloaded the source code. Try downloading again from the releases page.

https://github.com/nicholas-ross/SSMS-Schema-Folders/releases

**Comment by acappelletti** [comment]
Thanks! Now it works!
This are the right passages:

1. download the .zip file with source code
2. get-childitem "C:\Users\YOUR_USER\Downloads\SSMS-Schema-Folders-v1.5" | unblock-file
3. copy folder "SSMS Schema Folders" into "C:\Program Files (x86)\Microsoft SQL Server Management Studio 19\Common7\IDE\Extensions"
4. Lanch SSMS

ALEN
