### ISSUE TITLE
Extension not working in SSMS 19,3 even after unblocking

### ISSUE THREAD

**Issue by DominikMetz** [nicholas-ross/SSMS-Schema-Folders#45]
The extension does not start. But there is also no error message.
I am using the latest version.
I can't see the extension in the options either?
The files are located in the following folder: "C:\Program Files (x86)\Microsoft SQL Server Management Studio 19\Common7\IDE\Extensions\SSMS Schema Folders" 
There is no additional subfolder here.

**Comment by nicholas-ross** [comment]
You must unblock before extracting.

Do you see the below high-lighted value when going to `Tools > Options`?
![image](https://github.com/nicholas-ross/SSMS-Schema-Folders/assets/7508287/c7a31f80-d696-4bd1-9880-a637f89505d7)

**Comment by DominikMetz** [comment]
I unblock the zip before ectracting.
There is no entry in the options.

![image](https://github.com/nicholas-ross/SSMS-Schema-Folders/assets/85163184/04cff33d-44b7-4bcf-8bc2-2f0527e63063)


![image](https://github.com/nicholas-ross/SSMS-Schema-Folders/assets/85163184/3a1147b5-ca20-4487-ba3f-5b1a6e9009b4)

**Comment by eidylon** [comment]
> I unblock the zip before ectracting. There is no entry in the options.

Looks like your folder name is wrong. This is what it should be, and is working for me.

**Comment by DominikMetz** [comment]
I renamed the folder but no efect

**Comment by eidylon** [comment]
What are the contents of your folder? The fact it had the wrong name from the zip makes me question that. 
This is what should be in the folder : 

![image](https://github.com/nicholas-ross/SSMS-Schema-Folders/assets/5951045/ed0f1a11-5b87-42cd-b0a0-17d838a654b5)

**Comment by nicholas-ross** [comment]
You have downloaded the source code. Delete the folder and download the v1.5 zip file from the releases page. https://github.com/nicholas-ross/SSMS-Schema-Folders/releases/tag/v1.5

**Comment by DominikMetz** [comment]
Ok. That explains it. I downloaded this.
https://github.com/nicholas-ross/SSMS-Schema-Folders

Now it works. Thank you for the quick help.
