### ISSUE TITLE
SSMS 18

### ISSUE THREAD

**Issue by ahartman89** [nicholas-ross/SSMS-Schema-Folders#5]
Package does not work with SSMS 18, rendering SSMS 18 unusable without schema folders.

**Comment by nicholas-ross** [comment]
I've tested on a clean install of Windows 10 and SSMS 18 and it is working ok.

Make sure you unblock the zip file before extracting it. Right click on the zip file in Windows Explorer and go to properties. Click the `Unblock` button.

After extracting the zip file contents, copy the whole `SSMS Schema Folders` folder to `C:\Program Files (x86)\Microsoft SQL Server Management Studio 18\Common7\IDE\Extensions\SSMS Schema Folders`. All the .dll files are required for it to run, it will select the correct version at runtime.

Double check the .dll files are unblocked. For each .dll file in the `SSMS Schema Folders` folder, right click and go to properties. If you see the unblock button then click it. This needs to be done individually, the unblock button does not appear if selecting multiple files and then viewing properties.
