### ISSUE TITLE
SSMS v18.1 Cant drag objects from Object Explore

### ISSUE THREAD

**Issue by mthode88** [nicholas-ross/SSMS-Schema-Folders#9]
There is a bug in v18.1, possibly v18+ that doesn't allow you to drag an object from the object explorer to the query window.  It encounters and exception and locks up SSMS.

Stack Trace:
System.ObjectDisposedException: Cannot access a closed Stream.&#x000D;&#x000A;   at System.IO.__Error.StreamIsClosed()&#x000D;&#x000A;   at System.IO.MemoryStream.get_Length()&#x000D;&#x000A;   at System.Windows.Forms.DataObject.SaveStreamToHandle(IntPtr&amp; handle, Stream stream)&#x000D;&#x000A;   at System.Windows.Forms.DataObject.SaveDataToHandle(Object data, String format, STGMEDIUM&amp; medium)&#x000D;&#x000A;   at System.Windows.Forms.DataObject.GetDataIntoOleStructs(FORMATETC&amp; formatetc, STGMEDIUM&amp; medium)&#x000D;&#x000A;   at System.Windows.Forms.DataObject.System.Runtime.InteropServices.ComTypes.IDataObject.GetDataHere(FORMATETC&amp; formatetc, STGMEDIUM&amp; medium)&#x000D;&#x000A;   at System.Windows.Forms.DataObject.System.Runtime.InteropServices.ComTypes.IDataObject.GetData(FORMATETC&amp; formatetc, STGMEDIUM&amp; medium)&#x000D;&#x000A;   at System.Windows.DataObject.OleConverter.GetDataInner(FORMATETC&amp; formatetc, STGMEDIUM&amp; medium)&#x000D;&#x000A;   at System.Windows.DataObject.OleConverter.GetDataFromOleHGLOBAL(String format, DVASPECT aspect, Int32 index)&#x000D;&#x000A;   at System.Windows.DataObject.OleConverter.GetDataFromBoundOleDataObject(String format, DVASPECT aspect, Int32 index)&#x000D;&#x000A;   at System.Windows.DataObject.OleConverter.GetData(String format, Boolean autoConvert, DVASPECT aspect, Int32 index)&#x000D;&#x000A;   at System.Windows.DataObject.OleConverter.GetData(String format, Boolean autoConvert)&#x000D;&#x000A;   at System.Windows.DataObject.GetData(String format, Boolean autoConvert)&#x000D;&#x000A;   at System.Windows.DataObject.GetData(String format)&#x000D;&#x000A;   at Microsoft.VisualStudio.Editor.Implementation.Common.DataObjectHelper.ConvertToOleDataObject(IDataObject source)&#x000D;&#x000A;   at Microsoft.VisualStudio.Editor.Implementation.DragDrop.LanguageServiceTextDropHandler.IsDropEnabled(DragDropInfo dragDropInfo)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Editor.DragDrop.Implementation.DropHandlerManager.&lt;&gt;c__DisplayClass4_0.&lt;GetSupportingHandler&gt;b__0(IDropHandler handler)&#x000D;&#x000A;   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Editor.DragDrop.Implementation.DropHandlerManager.GetSupportingHandler(DragDropInfo dragDropInfo)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Editor.DragDrop.Implementation.DragDropStateManager.HandleFromStartToDragging(DragDropInfo dragDropInfo)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Editor.DragDrop.Implementation.DragDropStateManager.SetToDragging(DragDropInfo dragDropInfo)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Editor.DragDrop.Implementation.DragDropMouseProcessor.HandleDragEnter(DragDropInfo dragDropInfo, DragDropEffects&amp; resultingDragEffects)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Editor.DragDrop.Implementation.DragDropMouseProcessor.DoPreprocessDragEnter(DragEventArgs e, Point position)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Editor.DragDrop.Implementation.DragDropMouseProcessor.PreprocessDragEnter(DragEventArgs e)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.WpfMouseProcessor.&lt;&gt;c__DisplayClass46_0.&lt;UIElement_DragEnter&gt;b__0(IMouseProcessor p)&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.WpfMouseProcessor.&lt;&gt;c__DisplayClass56_1.&lt;MouseProcessorHandler&gt;b__0()&#x000D;&#x000A;   at Microsoft.VisualStudio.Text.Utilities.GuardedOperations.CallExtensionPoint(Object errorSource, Action call)

**Comment by nicholas-ross** [comment]
This is a known bug in SSMS. https://docs.microsoft.com/en-us/sql/ssms/release-notes-ssms?view=sql-server-2017#known-issues-181

Although it won't let you click the Ok button to dismiss the error, you can press enter and continue using SSMS.
